version: "3.7"
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8888:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        networks:
            - form

    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/app
        depends_on:
            - db
        networks:
            - form

    db:
        image: library/mysql:5.7.30
        container_name: form-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=data
            - MYSQL_USER=root
            - MYSQL_PASSWORD=pass
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "33062:3306"
        networks:
            - form

networks:
    form:
        driver: bridge

volumes:
    db-data:
